name: Mac Build

on: [push]

jobs:
  build_ssc:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{runner.workspace}}/build

      - name: Configure cmake
        working-directory: ${{runner.workspace}}/build
        run: cmake -DSAMAPI_EXPORT=OFF -DSAM_SKIP_TESTS=ON -DSAM_SKIP_TOOLS=ON ${{runner.workspace}}

      - name: Build SSC
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target ssc -j 2
